name: Lphy tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'
      #- name: Java Gradle Cache
      #  uses: actions/cache@v2
      #  with:
      #    path: |
      #      ./gradle/wrapper
      #     ./build-cache
      #    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #    restore-keys: |
      #      ${{ runner.os }}-gradle-
      - name: Run lphy unit tests
        run: ./gradlew :lphy:test --no-daemon
      - name: Run studio unit tests
        run: ./gradlew :lphy-studio:test --no-daemon
      #- name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      #  run: |
      #    ls ./gradle/
      #    ls ./build-cache/
      #    rm -f ./build-cache/*.lock
      #    rm -f ./build-cache/gc.properties
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: |
            lphy/build/test-results/**/*.xml
            lphy-studio/build/test-results/**/*.xml
