name: LPhy tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
      # clean
      - name: Clean
        run: mvn clean
      # test
      - name: Test
        run: mvn -B test --file pom.xml

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: |
            lphy/target/surefire-reports/**/*.xml
            lphy-base/target/surefire-reports/**/*.xml
            lphy-studio/target/surefire-reports/**/*.xml
