name: Lphy tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      # -x test
      - name: Execute Gradle build
        run: ./gradlew build

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: |
            lphy/build/test-results/**/*.xml
            lphy-studio/build/test-results/**/*.xml
