name: Lphy tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-lphy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          cache: 'gradle'
      - name: Java Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ./gradle/wrapper
            ./build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run unit tests
        # only available in lphy at the moment
        run: ./gradlew :lphy:test --no-daemon
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: lphy/build/test-results/**/*.xml